#!/bin/bash
echo "enter mark 1: "
read num1
echo "enter mark2:
read num2
echo "enter mark 3:
read num3
s=$((num1+num2+num3 ))
echo "your total mark is: "$s
avg=$((s/3))
echo "your avarage mark is: "Savg
if [ $avg>80 ]
then
echo "your grade is At
elif [ Savg 50 ]
then
echo "pass"
else
echo "fail"
fi
